#!/bin/bash

# ABANCOOL Production Deployment - Quick Reference Guide
# This file contains quick commands and procedures for production deployment

echo "=========================================="
echo "ABANCOOL Production Deployment Quick Guide"
echo "=========================================="
echo ""

# ========== ENVIRONMENT SETUP ==========
echo "1. ENVIRONMENT SETUP"
echo "===================="
echo ""
echo "Command: Load production environment"
echo "$ export $(cat .env.production | xargs)"
echo ""
echo "Verify environment variables:"
echo "$ echo \$DB_HOST \$DB_USER \$SMTP_HOST \$BULKSMS_API_TOKEN"
echo ""

# ========== DATABASE SETUP ==========
echo "2. DATABASE SETUP"
echo "================="
echo ""
echo "Database Information:"
echo "  Host: localhost"
echo "  User: kzinlgmw_Panda"
echo "  Password: Laban@2030"
echo "  Database: kzinlgmw_internal"
echo ""
echo "Run production database setup:"
echo "$ bash scripts/setup-production-db.sh"
echo ""
echo "Verify database tables:"
echo "$ mysql -h localhost -u kzinlgmw_Panda -p kzinlgmw_internal -e 'SHOW TABLES;'"
echo ""

# ========== EMAIL SETUP ==========
echo "3. EMAIL CONFIGURATION"
echo "======================"
echo ""
echo "Email Server Information:"
echo "  SMTP Host: mail.abancool.com"
echo "  SMTP Port: 465 (SSL/TLS)"
echo "  Username: noreply@abancool.com"
echo "  Password: Laban@2030"
echo ""
echo "IMAP Settings (for inbox monitoring):"
echo "  Host: mail.abancool.com"
echo "  Port: 993 (SSL/TLS)"
echo "  Username: noreply@abancool.com"
echo "  Password: Laban@2030"
echo ""

# ========== SMS SETUP ==========
echo "4. SMS CONFIGURATION (Bulk SMS / TalkSasa)"
echo "=========================================="
echo ""
echo "SMS Provider Information:"
echo "  API Endpoint: https://bulksms.talksasa.com/api/v3"
echo "  API Token: 2153|obu7jXdaPDyxCecwxopipnq9ofxX6TPElIQjOjEn211b1ea2"
echo "  Sender ID: ABAN_COOL"
echo "  Status: ACTIVE"
echo ""
echo "Test SMS with curl:"
echo ""
echo 'curl -X POST https://bulksms.talksasa.com/api/v3/sms/send \'
echo "  -H 'Authorization: Bearer 2153|obu7jXdaPDyxCecwxopipnq9ofxX6TPElIQjOjEn211b1ea2' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Accept: application/json' \\"
echo "  -d '{"
echo "    \"recipient\":\"254781000403\","
echo "    \"sender_id\":\"ABAN_COOL\","
echo "    \"type\":\"plain\","
echo "    \"message\":\"Test message from ABANCOOL\""
echo "  }'"
echo ""

# ========== DEPENDENCIES ==========
echo "5. INSTALL DEPENDENCIES"
echo "======================="
echo ""
echo "$ npm install"
echo ""
echo "Or install only production dependencies:"
echo "$ npm ci --production"
echo ""

# ========== MIGRATIONS ==========
echo "6. RUN DATABASE MIGRATIONS"
echo "=========================="
echo ""
echo "$ npm run migrate"
echo ""
echo "Or manually run migrations:"
echo "$ node server/src/index.js --migrate"
echo ""

# ========== SSL/TLS ==========
echo "7. SSL/TLS SETUP"
echo "==============="
echo ""
echo "Install SSL certificates:"
echo "$ sudo bash scripts/setup-ssl.sh api.abancool.com app.abancool.com"
echo ""

# ========== START APPLICATION ==========
echo "8. START APPLICATION"
echo "===================="
echo ""
echo "Start with PM2:"
echo "$ pm2 start ecosystem.config.js --env production"
echo ""
echo "Check status:"
echo "$ pm2 status"
echo ""
echo "View logs:"
echo "$ pm2 logs abancool-api"
echo ""

# ========== HEALTH CHECKS ==========
echo "9. HEALTH CHECKS"
echo "==============="
echo ""
echo "Check API health:"
echo "$ curl http://localhost:4000/api/health"
echo ""
echo "Check database health:"
echo "$ curl http://localhost:4000/api/health/db"
echo ""
echo "Check Redis health:"
echo "$ curl http://localhost:4000/api/health/redis"
echo ""

# ========== MONITORING ==========
echo "10. MONITORING & ALERTS"
echo "======================="
echo ""
echo "Check monitoring configuration:"
echo "$ pm2 start monitoring.config.js --name 'abancool-monitor'"
echo ""
echo "View monitoring logs:"
echo "$ pm2 logs abancool-monitor"
echo ""

# ========== BACKUP ==========
echo "11. BACKUP SETUP"
echo "==============="
echo ""
echo "Backup database:"
echo "$ bash scripts/deploy.sh backup"
echo ""
echo "Restore from backup:"
echo "$ bash scripts/rollback.sh <TIMESTAMP>"
echo ""

# ========== DEPLOYMENT ==========
echo "12. FULL DEPLOYMENT"
echo "==================="
echo ""
echo "Run complete deployment:"
echo "$ bash scripts/deploy.sh deploy"
echo ""

# ========== TESTING ==========
echo "13. RUN TESTS"
echo "============="
echo ""
echo "Run all tests:"
echo "$ npm test"
echo ""
echo "Run with coverage:"
echo "$ npm test -- --coverage"
echo ""
echo "Run specific test suite:"
echo "$ npm test -- server/tests/e2e.test.js"
echo ""
echo "Run performance tests:"
echo "$ npm test -- server/tests/performance.test.js"
echo ""

# ========== IMPORTANT FILES ==========
echo "14. IMPORTANT FILES & DIRECTORIES"
echo "=================================="
echo ""
echo "Configuration:"
echo "  .env.production          - Production environment variables"
echo "  PRODUCTION_CONFIG.md     - Complete configuration reference"
echo "  ecosystem.config.js      - PM2 configuration"
echo "  nginx/nginx.conf         - Nginx configuration"
echo ""
echo "Application:"
echo "  server/src/index.js      - Application entry point"
echo "  server/src/routes.js     - API routes (200+ endpoints)"
echo "  server/monitoring.config.js - Monitoring configuration"
echo ""
echo "Deployment:"
echo "  scripts/pre-deployment-check.sh - Pre-deployment validation"
echo "  scripts/setup-production-db.sh  - Database setup"
echo "  scripts/setup-ssl.sh           - SSL/TLS setup"
echo "  scripts/deploy.sh              - Deployment script"
echo "  scripts/rollback.sh            - Rollback script"
echo ""
echo "Documentation:"
echo "  PRODUCTION_RUNBOOK.md               - Complete operations guide"
echo "  server/TASK_27_IMPLEMENTATION_SUMMARY.md - Task documentation"
echo ""

# ========== USEFUL COMMANDS ==========
echo "15. USEFUL COMMANDS"
echo "==================="
echo ""
echo "View running processes:"
echo "$ pm2 status"
echo ""
echo "View real-time logs:"
echo "$ pm2 logs abancool-api -f"
echo ""
echo "Stop application:"
echo "$ pm2 stop abancool-api"
echo ""
echo "Restart application:"
echo "$ pm2 restart abancool-api"
echo ""
echo "View system resources:"
echo "$ htop"
echo ""
echo "Check disk usage:"
echo "$ df -h"
echo ""
echo "Check log files:"
echo "$ ls -lah /var/log/abancool/"
echo ""

# ========== MONITORING COMMANDS ==========
echo "16. MONITORING COMMANDS"
echo "======================="
echo ""
echo "Check API response time:"
echo "$ time curl http://localhost:4000/api/health"
echo ""
echo "Monitor network connections:"
echo "$ netstat -tlnp | grep 4000"
echo ""
echo "Check process memory usage:"
echo "$ ps aux | grep node"
echo ""
echo "Monitor database connections:"
echo "$ mysql -u kzinlgmw_Panda -p -e 'SHOW PROCESSLIST;'"
echo ""

# ========== TROUBLESHOOTING ==========
echo "17. TROUBLESHOOTING"
echo "==================="
echo ""
echo "If API is not responding:"
echo "  1. Check if process is running: pm2 status"
echo "  2. Check logs: pm2 logs abancool-api"
echo "  3. Check port: netstat -tlnp | grep 4000"
echo "  4. Restart service: pm2 restart abancool-api"
echo ""
echo "If database connection fails:"
echo "  1. Check MySQL is running: systemctl status mysql"
echo "  2. Test connection: mysql -h localhost -u kzinlgmw_Panda -p"
echo "  3. Check credentials in .env.production"
echo "  4. Verify database exists: SHOW DATABASES;"
echo ""
echo "If emails are not sending:"
echo "  1. Check SMTP credentials"
echo "  2. Verify firewall allows port 465"
echo "  3. Check email logs: pm2 logs | grep -i email"
echo "  4. Test SMTP: npm run test:email"
echo ""
echo "If SMS is not being sent:"
echo "  1. Verify API token in .env.production"
echo "  2. Check API endpoint accessibility"
echo "  3. Check SMS logs: pm2 logs | grep -i sms"
echo "  4. Test SMS: npm run test:sms"
echo ""

# ========== SLA & PERFORMANCE ==========
echo "18. SLA & PERFORMANCE TARGETS"
echo "============================="
echo ""
echo "API Uptime Target: 99.9%"
echo "Response Time (P95): 300ms"
echo "Response Time (P99): 500ms"
echo "Error Rate: < 0.5%"
echo "Database Query Time: < 200ms"
echo ""

# ========== CONTACTS ==========
echo "19. EMERGENCY CONTACTS"
echo "====================="
echo ""
echo "Admin Email: admin@abancool.com"
echo "Support Email: support@abancool.com"
echo "Billing Email: billing@abancool.com"
echo ""

echo "=========================================="
echo "For more information, see PRODUCTION_RUNBOOK.md"
echo "=========================================="
